DROP TABLE IF EXISTS passageiro CASCADE;
DROP TABLE IF EXISTS veiculo CASCADE;
DROP TABLE IF EXISTS motorista CASCADE;
DROP TABLE IF EXISTS corrida CASCADE;

CREATE TABLE passageiro (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR (50) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	saldo_em_conta DECIMAL(19,4) NOT NULL,
    numero_de_corridas int DEFAULT 0 NOT NULL,
	quantidade_de_avaliacoes int DEFAULT 0 NOT NULL,
	soma_das_notas int DEFAULT 0 NOT NULL,
    media_das_avaliacoes DOUBLE PRECISION DEFAULT 5 NOT NULL,
	data_nascimento DATE NOT NULL
);

ALTER TABLE passageiro ADD CONSTRAINT pk_passageiro PRIMARY KEY (id);
ALTER TABLE passageiro ADD CONSTRAINT chk_passageiro_cpf UNIQUE (cpf);
ALTER TABLE passageiro ADD CONSTRAINT chk_passageiro_credito CHECK (saldo_em_conta >= 0);
ALTER TABLE passageiro ADD CONSTRAINT chk_passageiro_idade CHECK ( AGE(data_nascimento) >= interval '16' year);
ALTER TABLE passageiro ADD CONSTRAINT chk_passageiro_tamanho_cpf CHECK (length(cpf) = 11);

CREATE TABLE motorista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(50) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    saldo_em_conta DECIMAL(19,4),
    habilitacao_numero VARCHAR(11) NOT NULL,
    habilitacao_categoria VARCHAR(1) NOT NULL,
    habilitacao_data_vencimento DATE NOT NULL,
    numero_de_corridas int DEFAULT 0 NOT NULL,
	quantidade_de_avaliacoes int DEFAULT 0 NOT NULL,
	soma_das_notas int DEFAULT 0 NOT NULL,
    media_das_avaliacoes DOUBLE PRECISION DEFAULT 5 NOT NULL
);

ALTER TABLE motorista ADD CONSTRAINT pk_motorista PRIMARY KEY (id);
ALTER TABLE motorista ADD CONSTRAINT uk_motorista_cpf UNIQUE (cpf);
ALTER TABLE motorista ADD CONSTRAINT chk_motorista_saldo CHECK (saldo_em_conta >= 0);
ALTER TABLE motorista ADD CONSTRAINT chk_motorista_idade CHECK (AGE(data_nascimento) >= interval '18' year);
ALTER TABLE motorista ADD CONSTRAINT chk_motorista_habilitacao_categoria CHECK (habilitacao_categoria IN ('A', 'B', 'C'));


CREATE TABLE veiculo (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	placa VARCHAR(7) NOT NULL,
	modelo VARCHAR(20) NOT NULL,
	cor VARCHAR (20) NOT NULL,
	foto_url VARCHAR (4000) NOT NULL,
	proprietario_id BIGINT NOT NULL,
	categoria VARCHAR(1) NOT NULL
);

ALTER TABLE veiculo ADD CONSTRAINT pk_veiculo PRIMARY KEY (id);
ALTER TABLE veiculo ADD CONSTRAINT uk_veiculo UNIQUE (proprietario_id);
ALTER TABLE veiculo ADD CONSTRAINT chk_veiculo_categoria CHECK (categoria IN ('A', 'B', 'C'));
ALTER TABLE veiculo ADD CONSTRAINT chk_veiculo_tamanho_placa CHECK (length(placa) = 7);
ALTER TABLE veiculo ADD CONSTRAINT fk_veiculo_proprietario FOREIGN KEY (proprietario_id) REFERENCES motorista;
ALTER TABLE veiculo ADD CONSTRAINT chk_veiculo_placa_unica UNIQUE(placa);


CREATE TABLE corrida (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	inicioX DECIMAL(10,8) NOT NULL,
	inicioY DECIMAL(10,8) NOT NULL,
	finalX DECIMAL(11,8) NOT NULL,
	finalY DECIMAL(11,8) NOT NULL,
	horario_inicio TIMESTAMP,
	horario_chegada TIMESTAMP,
	status VARCHAR(20) NOT NULL,
	motorista_id BIGINT,
	passageiro_id BIGINT NOT NULL,
	nota_motorista INT,
	nota_passageiro INT,
	valor_estimado DECIMAL(19,4),
	valor_total DECIMAL(19,4)
	
);

ALTER TABLE corrida ADD CONSTRAINT pk_corrida PRIMARY KEY (id);
ALTER TABLE corrida ADD CONSTRAINT fk_corrida_motorista FOREIGN KEY (motorista_id) REFERENCES  motorista;
ALTER TABLE corrida ADD CONSTRAINT fk_corrida_passageiro FOREIGN KEY (passageiro_id) REFERENCES passageiro;
ALTER TABLE corrida ADD CONSTRAINT chk_corrida_status CHECK (status IN ('SOLICITADA', 'INICIADA', 'FINALIZADA'));
